# Generated by Django 2.0.3 on 2018-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inform',
            name='id',
        ),
        migrations.AddField(
            model_name='inform',
            name='task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inform',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inform',
            name='group',
            field=models.CharField(choices=[('10706117', '10706117'), ('10703117', '10703117'), ('10703217', '10703217')], max_length=200),
        ),
    ]
